sudo: false

dist: xenial

language: generic

cache: apt

addons:
  apt:
    packages:
        - texlive
        - texlive-latex-extra
        - cm-super
        - latexmk
        - texlive-fonts-extra
        - tree
        

script:
    - latexmk -halt-on-error -interaction=nonstopmode
    
before_deploy:
  - latexmk -c 
  - cd dist/
  - ls
  - tree -H '.' -P '*.pdf' --charset utf-8 > index.html 

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  keep-history: false
  on:
    branch: master
